#static variables
gpu_id: 0
jatayu : False

# Hyperparams
lr : 2e-5
optimizer: "AdamW"
num_epochs: 10
prefix_length : 10
prefix_dim : 512
batch_size : 6
mle_bsz : 8
num_layers : 6
attn_heads : 8

warmup_steps : 5000

#training 
tokenizer : "gpt2"
train_method : "mle" # ['mle', 'scst']
log_train_metrics : False

#Boolean variables
logging : False
save_every_epoch : False
save_best_val : False
save_best_metric : True
normalize_prefix : True 
use_beam_search: False
freeze_gpt : True

# wandb related variables
wandb : 
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "img_cap_self_retrieval"
  run_name : "clip_mle"


#scst
train_sample_n : 2
cider_reward_weight : 1
bleu_reward_weight : 0
cached_tokens : 'coco-train-idxs'

#Sampling 
entry_count : 1
max_length : 67  # maximum number of words
top_p : 0.8
temp : 1
stop_token : '.'
method : "clip_cap"
lang_eval : 1
sampling_method : "sample"
eval_sample_n : 1
init_val : True

# Path variables
train_data : 'img_cap_self_retrieval_clip/data/new_train_cocodataset.pkl'
val_data : 'img_cap_self_retrieval_clip/data/new_val_cocodataset.pkl'
test_data : 'img_cap_self_retrieval_clip/data/new_test_cocodataset.pkl'
out_dir : 'img_cap_self_retrieval_clip/checkpoints/clip_ViT-B_32/'
cocotalk : 'img_cap_self_retrieval_clip/data/cocotalk.json'
