#dynamic variables
jatayu : True
batch_size : 6 #val:90s
mle_bsz : 8
train_method : "mle" # ['mle', 'scst']

# Hyperparams
lr : 2e-5
optimizer: "AdamW"
num_epochs: 10
prefix_length : 10
prefix_dim : 512
num_layers : 6
attn_heads : 8
warmup_steps : 5000

#training 
log_train_metrics : False

#Boolean variables
logging : True
save_every_epoch : False
save_best_val : False
save_best_metric : True
freeze_gpt : True

# wandb related variables
wandb : 
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "img_cap_self_retrieval"
  run_name : "clip_mle"


#scst
train_sample_n : 2
cider_reward_weight : 1
bleu_reward_weight : 0
cached_tokens : 'coco-train-idxs'

#Sampling 
method : "clip_cap"
sampling_method : "sample"
eval_sample_n : 1
init_val : True

# Path variables
train_data : 'data/new_train_cocodataset.pkl'
val_data : 'data/new_val_cocodataset.pkl'
test_data : 'data/new_test_cocodataset.pkl'
out_dir : 'checkpoints/clip_ViT-B_32/'
cocotalk : 'data/cocotalk.json'

#static variables
gpu_id: 0
tokenizer : "gpt2"
normalize_prefix : True 
use_beam_search: False
entry_count : 1
max_length : 67  # maximum number of words
top_p : 0.8
temp : 1
stop_token : '.'
lang_eval : 1
