#dynamic variables
jatayu : True
batch_size : 16
mle_bsz : 32
train_method : "mle" # ['mle', 'scst']
init_val : True

# Hyperparams
lr : 2e-5
optimizer: "AdamW"
num_epochs: 20
prefix_length : 10
prefix_dim : 512
num_layers : 8
attn_heads : 8
warmup_steps : 1000

#scst training

cider_reward_weight : 1
bleu_reward_weight : 0
cached_tokens : 'coco-train-idxs_gpt'
scst_lr : 1e-7
train_sample_n : 1
use_scheduler : False

#training 
log_train_metrics : False

#Boolean variables
logging : True
save_model : True
save_best_metric : True
freeze_gpt : True

# wandb related variables
wandb : 
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "img_cap_self_retrieval"
  run_name : "clip_mle_train_only_ln_with_dropout"

#Sampling 
method : "clip_cap"
sampling_method : "greedy"
eval_sample_n : 1

# Path variables
train_data : 'data/ViT-B_32_train_emb.pkl'
val_data : 'data/ViT-B_32_val_emb.pkl'
test_data : 'data/ViT-B_32_test_emb.pkl'
out_dir : 'checkpoints/clip_ViT-B_32/'
cocotalk : 'data/cocotalk.json'

#static variables
gpu_id: 0
tokenizer : "gpt2"
normalize_prefix : False 
use_beam_search: False
entry_count : 1
max_length : 67  # maximum number of words
top_p : 0.8
temp : 1
stop_token : '.'
lang_eval : 1

# Specific experiments (default = False)
reproduce_clipcap : False
train_only_ln : True